name: Docker Image CI

on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 0 * * 0"

jobs:
  publish:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Run Buildx
      run: >
        docker buildx build
        --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
        --tag navikey/raspbian-buster:${{ steps.date.outputs.date }},navikey/raspbian-buster:latest
        --push
        .
